### ISSUE TITLE
[BUG]: Seems v2 need v1?

### ISSUE THREAD

**Issue by kuchaguangjie** [shinokada/svelte-heros-v2#1]
### Description of the bug

use `svelte-heros-v2`, without v1, on start got error:
```
Cannot find module 'svelte-heros' imported from
'xxx/node_modules/.pnpm/flowbite-svelte@0.23.3/node_modules/flowbite-svelte/accordions/AccordionItem.svelte'
```
If v2 depends on v1 to work, then might should mention that in README.

But, IMO, v2 should not need v1, otherwise when import icon in .svelte file, it will show both icons, which may be a bit mess.

### Steps To Reproduce

- `pnpm rm svelte-heros`
- `pnpm add svelte-heros-v2@latest`
- `pnpm prune`
- `pnpm dev`
 on start, will get above error,

**Comment by shinokada** [comment]
Svelte-Heros-v2 doesn't have Svelte-Heros dependencies. [See package.json](https://github.com/shinokada/svelte-heros-v2/blob/main/package.json)

You need to run `pnpm i -D svelte-heros-v2`. Please read the [README](https://github.com/shinokada/svelte-heros-v2/blob/main/README.md)

**Comment by kuchaguangjie** [comment]
Ah ha, it's `flowbite-svelte` depends on `svelte-heros` v1 ..

**Comment by kuchaguangjie** [comment]
Upgrade to `flowbite-svelte` to `^0.26.3`, then it worked.
And, since the `icon` property of `<Sidebar>` is replaced by `<svelte:fragment slot="icon">` in new version, a bit code refactored is needed if upgrade from pretty old versions.

e.g
```
        <SidebarItem label="Home" href="/home">
          <svelte:fragment slot="icon">
            <Home variation="solid"/>
          </svelte:fragment>
        </SidebarItem>

**Comment by kuchaguangjie** [comment]
BTW, it should be `pnpm i -D svelte-heros-v2` , not `pnpm i svelte-heros-v2` I think. Since the readme use `npm i svelte-heros-v2@latest`, without `-D`.
