### ISSUE TITLE
[FEAT]: pass down svg attributes? 

### ISSUE THREAD

**Issue by wrabit** [shinokada/svelte-heros-v2#12]
### Description

Can we pass svg attributes? i.e. stroke-width="2"?

**Comment by shinokada** [comment]
Yes, I just updated and you can use the `strokeWidth` prop to change it.
Please update to svelte-heros-v2@0.3.17.

[REPL](https://svelte.dev/repl/e7036796b2554524bb012e6f72226360?version=3.55.1)

![image](https://user-images.githubusercontent.com/147320/217086175-b42673a4-d810-4090-bcb3-17fc8c5d177c.png)

**Comment by wrabit** [comment]
Looks good! thank you
