### ISSUE TITLE
[BUG]: strokeWidth defaults to 2 instead of 1.5

### ISSUE THREAD

**Issue by MCMattia** [shinokada/svelte-heros-v2#13]
### Description of the bug

Why does strokeWidth default to 2 whereas the icons from https://heroicons.com/ are always with strokeWidth of 1.5 ?

### Steps To Reproduce

Use an svg from https://heroicons.com/ and then use an Icon from svelte-heros-v2. You will see that the strokeWidth is different

**Comment by shinokada** [comment]
Fixed. svelte-heros-v2@0.3.19

**Comment by MCMattia** [comment]
Thank you for the rapid fix. The icons from svelte-heros-v2 are now with the same strokeWidth as the icons on https://heroicons.com/
