### ISSUE TITLE
[BUG]: Different Names than original

### ISSUE THREAD

**Issue by scrapix** [shinokada/svelte-heros-v2#14]
### Description of the bug

Hey, thank you fro your great work!

One question I have... why have you chosen different icon names than in the original library?

original: x-circle
svelte-heros-v2: XCircle

### Steps To Reproduce

Documentation

**Comment by shinokada** [comment]
You can create a component called My-component. But you can't import it as My-component.

```
// this works
import Mycomponent from './My-component.svelte'
// this won't work
import My-component from './My-component.svelte'
```

You have use your component name without `-`.
