### ISSUE TITLE
[FEAT]: Mini variation

### ISSUE THREAD

**Issue by Lorenium** [shinokada/svelte-heros-v2#16]
### Description

Would love to be able to use the "Mini" variation with all the icons. It's especially useful in header elements and form components. Saves time playing with the icon sizes and a lot of component libraries utilize it so it'd make it easier to implement them.
![image](https://github.com/shinokada/svelte-heros-v2/assets/57680600/d5bbe62c-bbb0-4931-b4ef-6ed05dcf970d)

**Comment by shinokada** [comment]
Can you try size="20"?

**Comment by shinokada** [comment]
Try `viewBox` and `variation` props and let me know:

```
<ChevronDown size="20" viewBox="0 0 20 20" variation="solid" class="ml-2 h-5 w-5 text-indigo-100" />
```

**Comment by Lorenium** [comment]
Left: 
```
<svg
  class="ml-2 h-5 w-5 text-indigo-100"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 20 20"
  fill="currentColor"
  aria-hidden="true"
>
  <path
    fill-rule="evenodd"
    d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
    clip-rule="evenodd"
  />
</svg>
```
Middle: `<ChevronDown size="20" viewBox="0 0 20 20" variation="solid" class="ml-2 h-5 w-5 text-indigo-100" />`
Right: `<ChevronDown size="20" class="ml-2 h-5 w-5 text-indigo-100" />`

![image](https://github.com/shinokada/svelte-heros-v2/assets/57680600/3655957c-65b3-4c2f-bb56-dde397137ae4)

**Comment by shinokada** [comment]
How about this?

```
<ChevronDown size="20" viewBox="0 0 20 20" variation="solid" class="ml-2 w-4 h-4 text-red-900" />
```

**Comment by Lorenium** [comment]
left one is still the mini variation svg path, the right ones are `w-4 h-4` and `w-3 h-3` in that order
![image](https://github.com/shinokada/svelte-heros-v2/assets/57680600/6a4b96c3-2fbe-4046-a18c-9adb64afbd32)

**Comment by shinokada** [comment]
Change the `strokeWidth` prop:

```
<ChevronDown size="20" viewBox="0 0 20 20" strokeWidth="2" class="ml-2 w-4 h-4 text-grey-900" />
```

**Comment by Lorenium** [comment]
Is there a reason you can't introduce a new variation? Just seems like there's no direct translation. I've played with the stroke width as well just doesn't translate easily at all.

**Comment by shinokada** [comment]
I need to update my script to add 20/solid for all icons.

**Comment by shinokada** [comment]
Can you try the latest and let me know?

```
pnpm I -D 'svelte-heros-v2@latest
```

**Comment by Lorenium** [comment]
Works great! Thanks a lot for the quick fix.
![image](https://github.com/shinokada/svelte-heros-v2/assets/57680600/953af210-74fc-4eb0-8341-975eebda01f3)

**Comment by shinokada** [comment]
Can you add `tabindex="-1"` to the button?

`tabindex="-1" ` when I use it as it is.
