### ISSUE TITLE
[FEAT]: explain the difference between this and svelte-hero-icons

### ISSUE THREAD

**Issue by dsm-72** [shinokada/svelte-heros-v2#17]
### Description

see title

**Comment by shinokada** [comment]
![image](https://github.com/shinokada/svelte-heros-v2/assets/147320/846bad6c-d63b-4260-b89b-d73deb0f05c1)
[Heroicons](https://heroicons.com/) have v1 and v2. [Svelte-heros](https://svelte-heros.codewithshin.com/) is v1 and this lib is v2. 
I have no idea about svelte-hero-icons.

**Comment by dsm-72** [comment]
@shinokada  thank you! I was confused about all the libs claiming to be hero icons for svelte >.<

**Comment by dsm-72** [comment]
by the way I am getting
```
rror: <MagnifyingGlassCircle> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <MagnifyingGlassCircle>.
```

**Comment by shinokada** [comment]
It works on REPL.

```
<script>
	import {MagnifyingGlassCircle} from 'svelte-heros-v2'
</script>

<MagnifyingGlassCircle size="100" />
```

![image](https://github.com/shinokada/svelte-heros-v2/assets/147320/dcf4a6b0-bdfc-4332-94cd-52e4aad0b1bd)

**Comment by shinokada** [comment]
I close the issue for now.
Feel free to open a new issue.
