### ISSUE TITLE
[BUG]: Solid Icons are not solid filled

### ISSUE THREAD

**Issue by dorisip** [shinokada/svelte-heros-v2#19]
### Description of the bug

Solid icons are no longer solid fill.

<img width="987" alt="image" src="https://github.com/shinokada/svelte-heros-v2/assets/4064480/84e6530b-8cff-4671-a1f6-af274bc3cca7">

### Steps To Reproduce

1. Pick the Star Icon
2. The Solid variation is not filled

```
<Icon name="star-solid" class="text-green-500" />
```

I'm trying to upgrade to v 0.8.2 and is seeing this regression.

**Comment by shinokada** [comment]
Thank you for letting me know.
Can you try the latest version? And let me know.

**Comment by shinokada** [comment]
Thank you for letting me know this. I will fix it asap.

**Comment by shinokada** [comment]
Can you update it to the latest version and let me know?
Since API has changed, please read the doc at https://svelte-heros-v2.vercel.app/.

**Comment by dorisip** [comment]
Looks good to me. Thanks

**Comment by dorisip** [comment]
Separate issue though - `strokeWidth` doesn't get bubble down properly

<img width="832" alt="image" src="https://github.com/shinokada/svelte-heros-v2/assets/4064480/48362e8d-38e4-4f6e-918b-1590a00a46ec">

**Comment by shinokada** [comment]
You are right. I will remove `stroke-width` from the exports.
