### ISSUE TITLE
[BUG]: svelte-heros-v2 increasing  bundle size

### ISSUE THREAD

**Issue by xmlking** [shinokada/svelte-heros-v2#20]
### Description of the bug

apparently  `svelte-heros-v2` adding 50% of my bundle size. 
is there a way to reduce this size?

<img width="1178" alt="image" src="https://github.com/shinokada/svelte-heros-v2/assets/627951/5ffad806-3466-44b2-af08-14bc7a90ef79">

<img width="924" alt="image" src="https://github.com/shinokada/svelte-heros-v2/assets/627951/4d980814-e98f-4a4f-9fd8-109293771911">

### Steps To Reproduce

N/A

### Additional Information

N/A

**Comment by shinokada** [comment]
Can you try the latest version?

**Comment by xmlking** [comment]
Using 	"svelte-heros-v2": "0.9.5",

**Comment by shinokada** [comment]
Maybe I need to go back to individual components rather than putting all path in a file.
Can you try v0.7.4 and let me know.

**Comment by shinokada** [comment]
The v0.10 should solve this problem.

**Comment by shinokada** [comment]
I'm sorry, it's a breaking change.

**Comment by xmlking** [comment]
no problem.  
Just for your reference, I switched to `flowbite-svelte-icons`  for the same project, The client icon bundle is `57.63 kB` and the server icon bundle size is `226.97 kB`  I am **OK** for this size for convenience for easy of use. 
 


<img width="1247" alt="image" src="https://github.com/shinokada/svelte-heros-v2/assets/627951/6a61e67c-5d37-41aa-a536-1b5473e72e0c">


<img width="1025" alt="image" src="https://github.com/shinokada/svelte-heros-v2/assets/627951/bcdf5693-19e5-47ec-8d4c-f5cd5b9364db">

**Comment by shinokada** [comment]
Since Flowbite icon library is increasing in number, I will change it to individual components in the future. It adds [extra benefits](https://github.com/shinokada/svelte-heros-v2#creating-global-default-icon) as well.
