### ISSUE TITLE
[FEAT]: Micro variations

### ISSUE THREAD

**Issue by jnraine** [shinokada/svelte-heros-v2#24]
### Description

Any plans to support the micro icons released in Heroicons 2.1.0?

https://github.com/tailwindlabs/heroicons/releases/tag/v2.1.0

### Additional Information

I've much appreciated this library, so thank you for building it.

**Comment by shinokada** [comment]
Yes, I can do that.

**Comment by shinokada** [comment]
I just added micro. Please update it the latest version and let me know.
