### ISSUE TITLE
[BUG]: Upgrading to V2 made my Svelteapp crash

### ISSUE THREAD

**Issue by michael** [shinokada/svelte-heros-v2#9]
### Description of the bug

Hey there. Thanks for creating this useful little module.

I've upgraded from V1 and spent quite some time troubleshooting why my app crashes with a "500 Internal server error", while there were no errors shown in the console.

The reason for the crash was that I referenced an icon `ArrowNarrowDown` that is no longer present in 
svelte-heros-v2. Possibly this is less a problem of this library but one of Vite or Sveltekit. Maybe you have an idea how I could dedect such a problem in the future.

Thanks a lot. Have a nice day! :) 

Michael

### Steps To Reproduce

1. Create a new Sveltekit app (latest Sveltekit version)
2. import { ArrowNarrowDown } from 'svelte-heros-v2';

**Comment by shinokada** [comment]
Heroicons v1 and v2 changed naming so it was inevitable.
You can see the [icon list](https://github.com/shinokada/svelte-heros-v2/blob/main/icon-list.md) to reference names.
